from __future__ import annotations

MAP_MEASUREMENT_SCHEMA = 15
OBS_WIDTH = 84
CART_WIDTH = 18
TEAM_WIDTH = 7
EVT_WIDTH = 18
EVENT_PUBLIC_TEAM = 0
STRATEGY_DEADLINE_S = 0.4
WEAPON_WORD_BITS = 24
CELL_EXTENT = 256

OBS = dict(
    ID=0, TEAM=1, HEALTH=2, ARMOR=3,
    AMMO_SHELLS=4, AMMO_BULLETS=5, AMMO_ROCKETS=6, AMMO_CELLS=7,
    AMMO_PLASMA=8, AMMO_FUEL=9,
    POS_X=10, POS_Y=11, POS_Z=12, VEL_X=13, VEL_Y=14, VEL_Z=15,
    WEAPONS_X=16, WEAPONS_Y=17, WEAPONS_Z=18,
    STRENGTH_FINISHED=19, SPAWN_TIME=20, ENGINE_TIME=21,
    CELL_X=22, CELL_Y=23, ALIVE=24, CONTROL=25,
    VIEW_FAULTS=26,
    VIEW_FAULT_SEQUENCE=27,
    SNAPSHOTS_SUPERSEDED=28,
    PRESENT=29,
    HAVOCBOT_KEYBOARDSKILL=30,
    BOT_MOVESKILL=31,
    BOT_DODGESKILL=32,
    BOT_PINGSKILL=33,
    BOT_WEAPONSKILL=34,
    BOT_AGGRESSKILL=35,
    BOT_RANGEPREFERENCE=36,
    BOT_AIMSKILL=37,
    BOT_OFFSETSKILL=38,
    RESPONSE_SEQ=39, RESPONSE_TIME=40, APPLIED_SEQUENCE=41, APPLICATION_LATENCY=42,
    BOT_MOUSESKILL=43,
    BOT_THINKSKILL=44,
    BOT_AISKILL=45,
    BOT_GLOBAL_SKILL=46,
    ENEMY_DAMAGE_DEALT=47, ENEMY_DAMAGE_TAKEN=48, ENEMY_KILLS=49,
    DEATHS=50, PICKUPS=51, CART_PUSH=52, CART_CONTEST=53,
    OUTCOME_A_SEQ=54,
    OUTCOME_A_ENEMY_DAMAGE_DEALT=55, OUTCOME_A_ENEMY_DAMAGE_TAKEN=56,
    OUTCOME_A_ENEMY_KILLS=57, OUTCOME_A_DEATHS=58, OUTCOME_A_PICKUPS=59,
    OUTCOME_A_CART_PUSH=60, OUTCOME_A_CART_CONTEST=61,
    OUTCOME_B_SEQ=62,
    OUTCOME_B_ENEMY_DAMAGE_DEALT=63, OUTCOME_B_ENEMY_DAMAGE_TAKEN=64,
    OUTCOME_B_ENEMY_KILLS=65, OUTCOME_B_DEATHS=66, OUTCOME_B_PICKUPS=67,
    OUTCOME_B_CART_PUSH=68, OUTCOME_B_CART_CONTEST=69,
    SWIZZLE_ACTIVE=70, SWIZZLE_EPOCH=71, SWIZZLE_PLAYER_COUNT=72,
    SWIZZLE_SPOT_COUNT=73, SWIZZLE_SLOT_COUNT=74, SWIZZLE_TICKET=75,
    SWIZZLE_COHORT=76, SWIZZLE_COHORT_COUNT=77, SWIZZLE_GENERATION=78,
    SWIZZLE_SCHEDULED_TIME=79, SWIZZLE_ACTUAL_TIME=80,
    SWIZZLE_LANE=81, SWIZZLE_SPOT=82, BOT_CONFIG_SCHEMA=83,
)
CS = dict(
    ID=0, PATH_POSITION=1, PATH_LENGTH=2, CONTROL_TEAM=3, SPEED=4,
    IDLE_TIME=5, LEAD_TEAM=6, SECOND_TEAM=7, HOME_TEAM=8,
    POS_X=9, POS_Y=10, POS_Z=11,
    SUPPORTS_PLAYER=12,
    TEAM_COUNT=13,
    ROLLBACK_ACTIVE=14,
    ROLLBACK_TARGET=15,
    CHECKPOINT_DEPTH=16, CHECKPOINT_COUNT=17,
)
TS = dict(ID=0, SCORE=1, CHECKPOINTS_HELD=2, CHECKPOINT_RATE=3, SCORE_LIMIT=4, EPISODE=5, FINISHED=6)
EVT = dict(
    KIND=0, TIME=1, OBSERVER=2, TEAM=3, SUBJECT=4,
    CELL_X=5, CELL_Y=6, TARGET_CELL_X=7, TARGET_CELL_Y=8,
    POS_X=9, POS_Y=10, POS_Z=11, RESPAWN_TIME=12, HEALTH=13,
    LINK_LENGTH=14, AMOUNT=15, RESPONSE_SEQ=16, EPISODE=17,
)
EVT_KIND = dict(
    ITEM_GONE=0, ITEM_HERE=1, ENEMY_HERE=2, RIVAL_HERE=3,
    CELL_LINK=4, DAMAGE=5, KILL=6, PICKUP=7, ROUND=8,
)
OUTCOME_NAMES = (
    "enemy_damage_dealt", "enemy_damage_taken", "enemy_kills", "deaths",
    "pickups", "cart_push", "cart_contest",
)
OBS_OUTCOME_COUNTER_COLUMNS = tuple((name, name.upper()) for name in OUTCOME_NAMES)
OBS_ROUTED_OUTCOME_GROUPS = tuple(
    (
        f"OUTCOME_{bank}_SEQ",
        tuple((name, f"OUTCOME_{bank}_{name.upper()}") for name in OUTCOME_NAMES),
    )
    for bank in ("A", "B")
)

BOT_CONFIGURATION_COLUMNS = ('HAVOCBOT_KEYBOARDSKILL', 'BOT_MOVESKILL', 'BOT_DODGESKILL', 'BOT_PINGSKILL', 'BOT_WEAPONSKILL', 'BOT_AGGRESSKILL', 'BOT_RANGEPREFERENCE', 'BOT_AIMSKILL', 'BOT_OFFSETSKILL', 'BOT_MOUSESKILL', 'BOT_THINKSKILL', 'BOT_AISKILL', 'BOT_GLOBAL_SKILL')

OBS_AMMO_COLUMNS = (
    "AMMO_SHELLS", "AMMO_BULLETS", "AMMO_ROCKETS",
    "AMMO_CELLS", "AMMO_PLASMA", "AMMO_FUEL",
)
OBS_WEAPON_COLUMNS = ("WEAPONS_X", "WEAPONS_Y", "WEAPONS_Z")
OBS_CATEGORICAL_COLUMNS = (
    "ID", "TEAM", "CELL_X", "CELL_Y",
    "RESPONSE_SEQ", "APPLIED_SEQUENCE",
    "OUTCOME_A_SEQ", "OUTCOME_B_SEQ",
    "SWIZZLE_EPOCH", "SWIZZLE_TICKET", "SWIZZLE_COHORT",
    "SWIZZLE_GENERATION", "SWIZZLE_LANE", "SWIZZLE_SPOT",
)
CART_CATEGORICAL_COLUMNS = (
    "ID", "CONTROL_TEAM", "LEAD_TEAM", "SECOND_TEAM", "HOME_TEAM",
)
def state_coordinate_kind(label):
    prefix, _, name = label.rpartition(".")
    column = name.upper()
    if prefix == "observation" and column in OBS_WEAPON_COLUMNS:
        return "bitset"
    if prefix == "observation" and column in OBS_CATEGORICAL_COLUMNS:
        return "categorical"
    if prefix.startswith("cart.") and column in CART_CATEGORICAL_COLUMNS:
        return "categorical"
    return "real"

def navigation_targets(realization):
    if "targets" in realization:
        return realization["targets"]
    voronoi = realization.get("voronoi", {})
    representatives = {}
    for node, cell in enumerate(voronoi.get("owner", range(len(realization["nodes"])))):
        if cell >= 0:
            representatives.setdefault(int(cell), node)
    sites = voronoi.get("site_nodes")
    return [{"id": cell, "node": int(sites[cell] if sites is not None else node),
             "position": list(realization["nodes"][sites[cell] if sites is not None else node][:3])}
            for cell, node in sorted(representatives.items())]
