

#include "weapon/blaster.qh"
#include "weapon/shotgun.qh"
#include "weapon/machinegun.qh"
#include "weapon/mortar.qh"
#include "weapon/minelayer.qh"
#include "weapon/electro.qh"
#include "weapon/crylink.qh"
#include "weapon/vortex.qh"
#include "weapon/hagar.qh"
#include "weapon/devastator.qh"

#include "weapon/porto.qh"
#include "weapon/vaporizer.qh"
#include "weapon/hook.qh"
#include "weapon/hlac.qh"
#include "weapon/tuba.qh"
#include "weapon/rifle.qh"
#include "weapon/fireball.qh"
#include "weapon/seeker.qh"
#include "weapon/shockwave.qh"
#include "weapon/arc.qh"

#define WEP_HARDCODED_IMPULSES 20
