const colors=['#4de3d1','#ffbd59','#639bff','#c487ff','#75dc82','#ff6f91']
const $=id=>document.getElementById(id)
const esc=value=>String(value??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const fmt=value=>Number.isFinite(+value)?(+value).toLocaleString(): '—'
const mean=values=>values.length?values.reduce((a,b)=>a+b,0)/values.length:0
let priorNodes={}

function canvas(id,draw){const el=$(id),ratio=devicePixelRatio||1,w=el.clientWidth,h=id==='phase'?330:230;el.style.height=h+'px';el.width=w*ratio;el.height=h*ratio;const ctx=el.getContext('2d');ctx.scale(ratio,ratio);draw(ctx,w,h)}
function axes(ctx,w,h,xlabel,ylabel){ctx.strokeStyle='#25313a';ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(34,i*h/5);ctx.lineTo(w-12,i*h/5);ctx.stroke()}ctx.fillStyle='#82909e';ctx.font='10px ui-monospace';ctx.fillText(xlabel,w-95,h-10);ctx.save();ctx.translate(12,110);ctx.rotate(-Math.PI/2);ctx.fillText(ylabel,0,0);ctx.restore()}
function range(values){const lo=Math.min(...values),hi=Math.max(...values);return [lo,hi===lo?lo+1:hi]}
function phase(rows){const points=rows.filter(r=>r.model).map(r=>{const a=r.assignments||[],wv=r.model.winner_value||[],lv=r.model.loser_value||[],win=[],lose=[];a.forEach((p,i)=>(p.team===r.PW?win:lose).push((p.team===r.PW?wv:lv)[i]||0));if(!win.length)win.push(...wv);return{x:mean(win),y:mean(lose),g:mean(a.map(p=>+p.gain||0)),pw:r.PW||1,t:r.t}});canvas('phase',(ctx,w,h)=>{axes(ctx,w,h,'W position retention','L hierarchy promotion');if(!points.length)return;const [xmin,xmax]=range(points.map(p=>p.x)),[ymin,ymax]=range(points.map(p=>p.y));const xy=p=>[38+(p.x-xmin)/(xmax-xmin)*(w-55),h-27-(p.y-ymin)/(ymax-ymin)*(h-45)];ctx.lineWidth=1.5;points.forEach((p,i)=>{if(!i)return;const [x0,y0]=xy(points[i-1]),[x,y]=xy(p);ctx.strokeStyle=colors[(p.pw-1)%colors.length]+'99';ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(x,y);ctx.stroke()});points.slice(-80).forEach((p,i)=>{const [x,y]=xy(p);ctx.fillStyle=colors[(p.pw-1)%colors.length];ctx.globalAlpha=.25+.75*i/80;ctx.beginPath();ctx.arc(x,y,2+Math.min(4,Math.abs(p.g)),0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1});$('phaseLegend').innerHTML=`<span>W ${points.at(-1)?.x.toFixed(4)}</span><span>L ${points.at(-1)?.y.toFixed(4)}</span><span>radius = selected policy gain</span>`}
function losses(rows){const fields=[['loss','#4de3d1'],['loss_pg','#ffbd59'],['loss_w','#639bff'],['loss_l','#c487ff'],['loss_dynamics','#ff5f63'],['loss_reg','#75dc82']];const series=fields.map(([key,color])=>({key,color,values:rows.map(r=>r.update?.[key]).map(Number)})).filter(s=>s.values.some(Number.isFinite));canvas('loss',(ctx,w,h)=>{axes(ctx,w,h,'updates','objective magnitude');const all=series.flatMap(s=>s.values.filter(Number.isFinite));if(!all.length)return;const [lo,hi]=range(all.map(v=>Math.sign(v)*Math.log10(1+Math.abs(v))));series.forEach(s=>{ctx.strokeStyle=s.color;ctx.lineWidth=1.5;ctx.beginPath();let begun=false;s.values.forEach((v,i)=>{if(!Number.isFinite(v))return;const x=35+i/Math.max(1,s.values.length-1)*(w-50),q=Math.sign(v)*Math.log10(1+Math.abs(v)),y=h-25-(q-lo)/(hi-lo)*(h-43);begun?ctx.lineTo(x,y):ctx.moveTo(x,y);begun=true});ctx.stroke()})});$('lossLegend').innerHTML=series.map(s=>`<span><i style="background:${s.color}"></i>${esc(s.key)} ${fmt(s.values.filter(Number.isFinite).at(-1)?.toPrecision(4))}</span>`).join('')}
function mesh(nodes){$('mesh').innerHTML=nodes.map((n,i)=>{const old=priorNodes[n.node]||n,ds=(n.sent||0)-(old.sent||0),dr=(n.recvd||0)-(old.recvd||0);priorNodes[n.node]=n;return `<div class="node"><div class="node-head"><strong>NODE ${fmt(n.node)}</strong><span style="color:${n.up?'var(--cyan)':'var(--red)'}">${n.up?'UP':'DOWN'}</span></div><div class="node-data"><div><span>sent</span><b>${fmt(n.sent)}</b></div><div><span>received</span><b>${fmt(n.recvd)}</b></div><div><span>Δ tx/rx</span><b>${ds}/${dr}</b></div><div><span>bad</span><b>${fmt(n.bad)}</b></div></div></div>`}).join('<div class="link"><span>OBS / CART / EVT</span><div class="link-line"></div><span>STRATEGY RESPONSE</span></div>')}
function carts(row){$('carts').innerHTML=(row.carts||[]).map((c,i)=>`<div class="cart"><div class="cart-head"><b>CART ${esc(c.id)}</b><span style="color:${colors[(Math.max(1,c.ctrl)-1)%colors.length]}">TEAM ${esc(c.ctrl)}</span></div><div class="track"><i style="width:${Math.max(1,+c.depth*100)}%;background:${colors[(Math.max(1,c.ctrl)-1)%colors.length]}"></i></div><div class="cart-meta">depth ${(+c.depth).toFixed(4)} · progress ${(+c.progress).toFixed(3)} · speed ${(+c.speed).toFixed(3)}</div></div>`).join('');$('succession').textContent=(row.SUCC||[]).map(v=>`T${v[0]} ${v[1]}`).join(' · ')}
function tensors(row){const model=row.model||{};$('tensors').innerHTML=Object.entries(model.shapes||{}).map(([name,shape])=>`<div class="tensor ${model.finite?.[name]?'':'bad'}"><b>${esc(name)}</b><span>${esc(shape.join(' × '))}</span><span>[${(model.range?.[name]||[]).map(v=>fmt(v)).join(', ')}] · ${model.finite?.[name]?'finite':'NON-FINITE'}</span></div>`).join('')}
function resources(row){$('resources').innerHTML=(row.resources||[]).map((r,i)=>`<div class="resource" style="--team:${colors[i%colors.length]}"><h3>TEAM ${r.team} · ${r.alive}/${r.players} alive</h3><div class="resource-grid"><span>health<b>${fmt(r.health)}</b></span><span>armor<b>${fmt(r.armor)}</b></span><span>ammo<b>${fmt(r.ammo)}</b></span><span>weapons<b>${fmt(r.weapon_slots)}</b></span><span>speed<b>${fmt(r.mean_speed)}</b></span><span>power<b>${fmt(r.power)}</b></span></div></div>`).join('')}
function assignments(row){$('assignments').innerHTML=(row.assignments||[]).map(a=>`<tr><td>#${a.edict}</td><td>T${a.team} <span class="role ${a.team===row.PW?'W':'L'}">${a.team===row.PW?'W':'L'}</span></td><td>${a.controller} / ${a.behavior}</td><td>${esc(a.kind)}</td><td>${a.subject}</td><td>${(+a.target).toFixed(3)}</td><td>${(+a.gain).toFixed(3)}</td><td>${(+a.commit).toFixed(3)}</td></tr>`).join('');$('offpolicy').textContent=`${row.off_policy_players||0} off-policy players this frame`}
function focus(row){const m=row.strategy_focus||[],max=Math.max(1,...m.flat());$('focus').innerHTML=m.map((line,i)=>`<div class="focus-row" style="grid-template-columns:repeat(${line.length},1fr)">${line.map((v,j)=>`<div class="focus-cell" style="background:rgba(77,227,209,${.07+.75*v/max})">T${i+1}→T${j+1}<br>${v}</div>`).join('')}</div>`).join('')}
function violations(data,row){const out=[];if(data.error)out.push(data.error);if(!data.games.length)out.push('No local Xonotic dedicated process observed');if(data.games.length>1)out.push(`${data.games.length} Xonotic producers share an unnamespaced strategy channel`);if(!data.responders?.length)out.push('No remote strategy responder observed');if(data.source_age>5)out.push(`Telemetry is ${data.source_age.toFixed(1)}s old`);data.nodes.forEach(n=>{if(!n.up)out.push(`Mesh node ${n.node??n.host} is down: ${n.error||'status unavailable'}`);if(n.bad)out.push(`Mesh node ${n.node} reports ${n.bad} bad frames`)});const ids=(row.carts||[]).map(c=>c.id);if(new Set(ids).size!==ids.length)out.push(`Duplicate cart identities: ${ids.join(', ')}`);Object.entries(row.model?.finite||{}).forEach(([k,v])=>{if(!v)out.push(`Non-finite values in ${k}`)});const expected={x:[row.l,48],beta:[row.l,8],ir:[row.l,128],gram:[row.l,row.l]};Object.entries(expected).forEach(([k,v])=>{const got=row.model?.shapes?.[k];if(got&&got.join()!=v.join())out.push(`${k} shape ${got.join('×')} != ${v.join('×')}`)});if((row.assignments||[]).length!==row.l)out.push(`Assignments ${row.assignments?.length||0} != participants ${row.l}`);$('violations').innerHTML=out.length?out.map(v=>`<div class="violation">${esc(v)}</div>`).join(''):'<div class="clear">No observed type, transport, identity, or cardinality violation in this frame.</div>'}
function render(data){const rows=data.rows||[],row=rows.at(-1)||{},cadence=rows.length>1?Math.max(0,rows.at(-1).t-rows.at(-2).t):Infinity,active=rows.length&&data.nodes.every(n=>n.up)&&data.games.length===1&&data.responders?.length&&data.source_age<5;$('live').className='live '+(active?'ok':'bad');$('live').querySelector('span').textContent=active?'LIVE CROSS-RDMA':'RUNTIME DEGRADED';$('environment').textContent=row.environment||'—';$('responses').textContent=fmt(row.resp_id);$('updates').textContent=fmt(row.updates);$('shape').textContent=row.k?`${row.k}T · ${row.j}C · ${row.l}P`:'—';$('winner').textContent=row.PW?`TEAM ${row.PW} · W policy`:'UNRESOLVED';$('age').textContent=rows.length?`${cadence.toFixed(3)}s / ${(+data.source_age).toFixed(1)}s old`:'—';$('game').textContent=data.games.length===1?'GAME SERVER LIVE':`${data.games.length} GAME SERVERS`;$('game').style.color=data.games.length===1?'var(--cyan)':'var(--red)';$('source').textContent=data.source||'';mesh(data.nodes||[]);phase(rows);losses(rows);carts(row);tensors(row);resources(row);assignments(row);focus(row);violations(data,row)}
async function refresh(){try{const response=await fetch('/api/live',{cache:'no-store'});render(await response.json())}catch(error){$('live').className='live bad';$('live').querySelector('span').textContent='VIEWER DISCONNECTED';$('violations').innerHTML=`<div class="violation">${esc(error)}</div>`}}
refresh();setInterval(refresh,2000);addEventListener('resize',()=>refresh())
