#include "slider_decibels.qh"

float toDecibelOfSquare(float f, float mi)
{
	float A = log(10) / 20;
	if(mi != 0)
	{

		float t = 1 / A + mi;
		float u = exp(1 + A * mi);
		if(f <= u)
			return mi + (t - mi) * (f / u);
	}
	return log(f) / A;
}

float fromDecibelOfSquare(float f, float mi)
{
	float A = log(10) / 20;
	if(mi != 0)
	{

		float t = 1 / A + mi;
		float u = exp(1 + A * mi);
		if(f <= t)
			return u * ((f - mi) / (t - mi));
	}
	return exp(A * f);
}

entity makeXonoticDecibelsSlider_T(float theValueMin, float theValueMax, float theValueStep, string theCvar, string theTooltip)
{
	entity me;
	me = NEW(XonoticDecibelsSlider);
	me.configureXonoticSlider(me, theValueMin, theValueMax, theValueStep, theCvar, theTooltip);
	return me;
}
entity makeXonoticDecibelsSlider(float theValueMin, float theValueMax, float theValueStep, string theCvar)
{
	return makeXonoticDecibelsSlider_T(theValueMin, theValueMax, theValueStep, theCvar, string_null);
}
void XonoticDecibelsSlider_loadCvars(entity me)
{
	float v;

	if (!me.controlledCvar)
		return;

	v = cvar(me.controlledCvar);

	if(v > fromDecibelOfSquare(me.valueMax - 0.5 * me.valueStep, me.valueMin))
		Slider_setValue_noAnim(me, me.valueMax);
	else
		Slider_setValue_noAnim(me, me.valueStep * floor(0.5 + toDecibelOfSquare(v, me.valueMin) / me.valueStep));
}
void XonoticDecibelsSlider_saveCvars(entity me)
{
	if (!me.controlledCvar)
		return;

	if(me.value > me.valueMax - 0.5 * me.valueStep)
		cvar_set(me.controlledCvar, ftos(fromDecibelOfSquare(me.valueMax, me.valueMin)));
	else
		cvar_set(me.controlledCvar, ftos(fromDecibelOfSquare(me.value, me.valueMin)));
}

float autocvar_menu_snd_sliderscale;
string XonoticDecibelsSlider_valueToText(entity me, float v)
{
	if(v > me.valueMax - 0.5 * me.valueStep)
		return CTX(_("VOL^MAX"));
	else if(v <= me.valueMin)
		return CTX(_("VOL^OFF"));
	else if(autocvar_menu_snd_sliderscale == 3)
		return sprintf("%d %%", (v - me.valueMin) / (me.valueMax - me.valueMin) * 100);
	else if(autocvar_menu_snd_sliderscale == 2)
		return sprintf("%.1f", (v - me.valueMin) / (me.valueMax - me.valueMin) * 10);
	else if(autocvar_menu_snd_sliderscale == 1)
		return sprintf("%.2f %%", fromDecibelOfSquare(v, me.valueMin) * 100);
	else
		return sprintf(_("%s dB"), ftos_decimals(toDecibelOfSquare(fromDecibelOfSquare(v, me.valueMin), 0), me.valueDigits));
}
