

float MOVE_NORMAL = 0;
float MOVE_NOMONSTERS = 1;
float MOVE_MISSILE = 2;

float(string s) checkextension = #99;

.float buttonchat;

.float buttonuse;

float   EF_ADDITIVE     = 32;

float   EF_BLUE         = 64;

float EF_DOUBLESIDED = 32768;

float   EF_DYNAMICMODELLIGHT     = 131072;

float   EF_FLAME        = 1024;

float   EF_FULLBRIGHT   = 512;

float   EF_NODEPTHTEST       = 8192;

float   EF_NODRAW       = 16;

float   EF_NOGUNBOB     = 256;

float   EF_NOSHADOW     = 4096;

float   EF_RED          = 128;

float   EF_RESTARTANIM_BIT = 1048576;

float   EF_STARDUST     = 2048;

float   EF_TELEPORT_BIT = 2097152;

.float alpha;

.vector colormod;

.entity exteriormodeltoclient;

.float glow_color;
.float glow_size;
.float glow_trail;

.vector glowmod;

float EF_LOWPRECISION = 4194304;

.float scale;

.float traileffectnum;

.entity viewmodelforclient;

.entity tag_entity;
.float tag_index;

void(entity e, entity tagentity, string tagname) setattachment = #443;

.float button3;
.float button4;
.float button5;
.float button6;
.float button7;
.float button8;
.float button9;
.float button10;
.float button11;
.float button12;
.float button13;
.float button14;
.float button15;
.float button16;

float MOVETYPE_FLY_WORLDONLY = 33;

float MOVETYPE_FOLLOW = 12;

float DEG2RAD = 0.0174532925199432957692369076848861271344287188854172545609719144;
float RAD2DEG = 57.2957795130823208767981548141051703324054724665643215491602438612;
float PI      = 3.1415926535897932384626433832795028841971693993751058209749445923;

float(float s) asin = #471;
float(float c) acos = #472;
float(float t) atan = #473;
float(float c, float s) atan2 = #474;
float(float a) tan = #475;

.float idealpitch;
.float pitch_speed;

void(entity ent) changepitch = #63;

void(entity from, entity to) copyentity = #400;

float(float caseinsensitive, string s, ...) crc16 = #494;

string(string s) cvar_defstring = #482;

string(string name) cvar_description = #518;

string(string s) cvar_string = #448;

float(string name) cvar_type = #495;
float CVAR_TYPEFLAG_EXISTS = 1;
float CVAR_TYPEFLAG_SAVED = 2;
float CVAR_TYPEFLAG_PRIVATE = 4;
float CVAR_TYPEFLAG_ENGINE = 8;
float CVAR_TYPEFLAG_HASDESCRIPTION = 16;
float CVAR_TYPEFLAG_READONLY = 32;

string(string digest, string data, ...) digest_hex = #639;

entity(float entnum) edict_num = #459;
float(entity ent) wasfreed = #353;

float() numentityfields = #496;
string(float fieldnum) entityfieldname = #497;
float(float fieldnum) entityfieldtype = #498;
string(float fieldnum, entity ent) getentityfieldstring = #499;
float(float fieldnum, entity ent, string s) putentityfieldstring = #500;

float FIELD_STRING   = 1;
float FIELD_FLOAT    = 2;
float FIELD_VECTOR   = 3;
float FIELD_ENTITY   = 4;
float FIELD_FUNCTION = 6;

void(string s) loadfromdata = #529;
void(string s) loadfromfile = #530;
void(string s) callfunction = #605;
void(float fh, entity e) writetofile = #606;
float(string s) isfunction = #607;
void(entity e, string s) parseentitydata = #608;

string(entity ent) etos = #65;

string(void) getextresponse = #624;

entity(.string fld, string match) findchain = #402;

entity(vector org, float rad, .entity tofield) findradius_tofield = #22;
entity(.string fld, string match, .entity tofield) findchain_tofield = #402;
entity(.float fld, float match, .entity tofield) findchainflags_tofield = #450;
entity(.float fld, float match, .entity tofield) findchainfloat_tofield = #403;

entity(.float fld, float match) findchainflags = #450;

entity(.entity fld, entity match) findchainentity = #403;
entity(.float fld, float match) findchainfloat = #403;

entity(entity start, .float fld, float match) findflags = #449;

entity(entity start, .entity fld, entity match) findentity = #98;
entity(entity start, .float fld, float match) findfloat = #98;

float(string pattern, float caseinsensitive, float quiet) search_begin = #444;
void(float handle) search_end = #445;
float(float handle) search_getsize = #446;
string(float handle, float num) search_getfilename = #447;

vector(vector org) getlight = #92;

float(entity e, float s) getsurfacenumpoints = #434;
vector(entity e, float s, float n) getsurfacepoint = #435;
vector(entity e, float s) getsurfacenormal = #436;
string(entity e, float s) getsurfacetexture = #437;
float(entity e, vector p) getsurfacenearpoint = #438;
vector(entity e, float s, vector p) getsurfaceclippedpoint = #439;

float SPA_POSITION = 0;
float SPA_S_AXIS = 1;
float SPA_T_AXIS = 2;
float SPA_R_AXIS = 3;
float SPA_TEXCOORDS0 = 4;
float SPA_LIGHTMAP0_TEXCOORDS = 5;
float SPA_LIGHTMAP0_COLOR = 6;

vector(entity e, float s, float n, float a) getsurfacepointattribute = #486;

float(entity e, float s) getsurfacenumtriangles = #628;
vector(entity e, float s, float n) getsurfacetriangle = #629;

float(entity ent, string tagname) gettagindex = #451;
vector(entity ent, float tagindex) gettaginfo = #452;

float gettaginfo_parent;
string gettaginfo_name;
vector gettaginfo_offset;
vector gettaginfo_forward;
vector gettaginfo_right;
vector gettaginfo_up;

float GETTIME_FRAMESTART = 0;
float GETTIME_REALTIME = 1;
float GETTIME_HIRES = 2;
float GETTIME_UPTIME = 3;

float(float tmr) gettime = #519;

float GETTIME_CDTRACK = 4;

float log(float f) = #532;

float(float a, float b, ...) min = #94;
float(float a, float b, float c) min3 = #94;
float(float a, float b, float c, float d) min4 = #94;
float(float a, float b, float c, float d, float e) min5 = #94;
float(float a, float b, float c, float d, float e, float f) min6 = #94;
float(float a, float b, float c, float d, float e, float f, float g) min7 = #94;
float(float a, float b, float c, float d, float e, float f, float g, float h) min8 = #94;
float(float a, float b, ...) max = #95;
float(float a, float b, float c) max3 = #95;
float(float a, float b, float c, float d) max4 = #95;
float(float a, float b, float c, float d, float e) max5 = #95;
float(float a, float b, float c, float d, float e, float f) max6 = #95;
float(float a, float b, float c, float d, float e, float f, float g) max7 = #95;
float(float a, float b, float c, float d, float e, float f, float g, float h) max8 = #95;
float(float minimum, float val, float maximum) bound = #96;

float(entity num) num_for_edict = #512;

vector() randomvec = #91;

float(float val) sin = #60;
float(float val) cos = #61;
float(float val) sqrt = #62;
float(float a, float b) pow = #97;

string(string format, ...) sprintf = #627;

string(float uselocaltime, string format, ...) strftime = #478;

float(string s) strlennocol = #476;
string(string s) strdecolorize = #477;

string(string s) strtolower = #480;
string(string s) strtoupper = #481;

float(string s, string separator1, ...) tokenizebyseparator = #479;

float(string s) tokenize_console = #514;
float(float i) argv_start_index = #515;
float(float i) argv_end_index = #516;

void(vector v1, vector min, vector max, vector v2, float nomonsters, entity forent) tracebox = #90;

void(entity ent, entity ignore) tracetoss = #64;

float MOVE_HITMODEL = 4;

float MOVE_WORLDONLY = 3;

vector(vector forward, vector up) vectoangles2 = #51;

void(vector dir) vectorvectors = #432;

string(string filename) whichpack = #503;

string(string in) uri_escape = #510;
string(string in) uri_unescape = #511;

float(string url, float id) uri_get = #513;

float(string url, float id, string content_type, string data) uri_post = #513;
float(string url, float id, string content_type, string delim, float buf) uri_postbuf = #513;

float(string name, string value) registercvar = #93;

void(entity e, float chan, string samp, float vol, float atten, float speed, float flags) sound7 = #8;
float SOUNDFLAG_RELIABLE = 1;

float(entity e, float channel) getsoundtime = #533;
float(string sample) soundlength = #534;

float SOLID_CORPSE = 5;

float CLIENTTYPE_DISCONNECTED = 0;
float CLIENTTYPE_REAL = 1;
float CLIENTTYPE_BOT = 2;
float CLIENTTYPE_NOTACLIENT = 3;

entity() spawnclient = #454;
float(entity clent) clienttype = #455;

.float bouncefactor;
.float bouncestop;

.entity clientcamera;

.float clientcolors;

.float() customizeentityforclient;

.float disableclientprediction;

.float discardabledemo;

.entity drawonlytoclient;

void(entity clent) dropclient = #453;

void(vector org, string modelname, float startframe, float endframe, float framerate) effect = #404;

.void(float nOriginalContents, float nNewContents) contentstransition;

.void(vector vImpactVelocity) movetypesteplandevent;

void(vector origin, string sample, float volume, float attenuation) pointsound = #483;

.float modelflags;

float EF_NOMODELFLAGS = 8388608;
float MF_ROCKET  =   1;
float MF_GRENADE =   2;
float MF_GIB     =   4;
float MF_ROTATE  =   8;
float MF_TRACER  =  16;
float MF_ZOMGIB  =  32;
float MF_TRACER2 =  64;
float MF_TRACER3 = 128;

.string netaddress;

.entity nodrawtoclient;

.float ping;

.float ping_packetloss;
.float ping_movementloss;

float(string effectname) particleeffectnum = #335;
void(entity ent, float effectnum, vector start, vector end) trailparticles = #336;
void(float effectnum, vector org, vector vel, float howmany) pointparticles = #337;

.vector punchvector;

.vector movement;

const float MOVETYPE_PHYSICS = 32;

const float SOLID_PHYSICS_BOX = 32;
const float SOLID_PHYSICS_SPHERE = 33;
const float SOLID_PHYSICS_CAPSULE = 34;
const float SOLID_PHYSICS_TRIMESH = 35;
const float SOLID_PHYSICS_CYLINDER = 36;

const float GEOMTYPE_NONE = -1;
const float GEOMTYPE_SOLID = 0;
const float GEOMTYPE_BOX = 1;
const float GEOMTYPE_SPHERE = 2;
const float GEOMTYPE_CAPSULE = 3;
const float GEOMTYPE_TRIMESH = 4;
const float GEOMTYPE_CYLINDER = 5;

const float GEOMTYPE_CAPSULE_X = 6;
const float GEOMTYPE_CAPSULE_Y = 7;
const float GEOMTYPE_CAPSULE_Z = 8;
const float GEOMTYPE_CYLINDER_X	= 9;
const float GEOMTYPE_CYLINDER_Y	= 10;
const float GEOMTYPE_CYLINDER_Z	= 11;

const float JOINTTYPE_NONE = 0;
const float JOINTTYPE_POINT = 1;
const float JOINTTYPE_HINGE = 2;
const float JOINTTYPE_SLIDER = 3;
const float JOINTTYPE_UNIVERSAL = 4;
const float JOINTTYPE_HINGE2 = 5;
const float JOINTTYPE_FIXED = -1;

const float FORCETYPE_NONE = 0;
const float FORCETYPE_FORCE = 1;
const float FORCETYPE_FORCEATPOS = 2;
const float FORCETYPE_TORQUE = 3;

.float  geomtype;
.float  maxcontacts;
.float  mass;
.vector massofs;
.float  friction;
.float  bouncefactor;
.float  bouncestop;
.float  jointtype;
.float  forcetype;
.float  erp;

void(entity e, float physics_enabled) physics_enable = #540;
void(entity e, vector force, vector force_pos) physics_addforce = #541;
void(entity e, vector torque) physics_addtorque = #542;

void(string s, ...) print = #339;

string worldstatus;

.string clientstatus;

void(entity ent, float colors) setcolor = #401;

void(float to, string s, float sz) WritePicture = #501;

void(float to, string s) WriteUnterminatedString = #456;

void(vector org, vector velocity, float howmany) te_blood = #405;

float TE_BLOOD = 50;

void(vector mincorner, vector maxcorner, float explosionspeed, float howmany) te_bloodshower = #406;

void(vector org, float radius, float lifetime, vector color) te_customflash = #417;

void(vector org, vector color) te_explosionrgb = #407;

void(vector org, vector vel, float howmany) te_flamejet = #457;

void(vector mincorner, vector maxcorner, vector vel, float howmany, float color, float gravityflag, float randomveljitter) te_particlecube = #408;

void(vector mincorner, vector maxcorner, vector vel, float howmany, float color) te_particlerain = #409;

void(vector mincorner, vector maxcorner, vector vel, float howmany, float color) te_particlesnow = #410;

void(vector org) te_plasmaburn = #433;

void(vector org) te_gunshotquad = #412;
void(vector org) te_spikequad = #413;
void(vector org) te_superspikequad = #414;
void(vector org) te_explosionquad = #415;

void(vector org) te_smallflash = #416;

void(vector org, vector vel, float howmany) te_spark = #411;

void(vector org) te_gunshot = #418;
void(vector org) te_spike = #419;
void(vector org) te_superspike = #420;
void(vector org) te_explosion = #421;
void(vector org) te_tarexplosion = #422;
void(vector org) te_wizspike = #423;
void(vector org) te_knightspike = #424;
void(vector org) te_lavasplash = #425;
void(vector org) te_teleport = #426;
void(vector org, float color, float colorlength) te_explosion2 = #427;
void(entity own, vector start, vector end) te_lightning1 = #428;
void(entity own, vector start, vector end) te_lightning2 = #429;
void(entity own, vector start, vector end) te_lightning3 = #430;
void(entity own, vector start, vector end) te_beam = #431;

.float dphitcontentsmask;
float trace_dpstartcontents;
float trace_dphitcontents;
float trace_dphitq3surfaceflags;
string trace_dphittexturename;

float DPCONTENTS_SOLID = 1;
float DPCONTENTS_WATER = 2;
float DPCONTENTS_SLIME = 4;
float DPCONTENTS_LAVA = 8;
float DPCONTENTS_SKY = 16;
float DPCONTENTS_BODY = 32;
float DPCONTENTS_CORPSE = 64;
float DPCONTENTS_NODROP = 128;
float DPCONTENTS_PLAYERCLIP = 256;
float DPCONTENTS_MONSTERCLIP = 512;
float DPCONTENTS_DONOTENTER = 1024;
float DPCONTENTS_LIQUIDSMASK = 14;
float DPCONTENTS_BOTCLIP = 2048;
float DPCONTENTS_OPAQUE = 4096;
float Q3SURFACEFLAG_NODAMAGE = 1;
float Q3SURFACEFLAG_SLICK = 2;
float Q3SURFACEFLAG_SKY = 4;
float Q3SURFACEFLAG_LADDER = 8;
float Q3SURFACEFLAG_NOIMPACT = 16;
float Q3SURFACEFLAG_NOMARKS = 32;
float Q3SURFACEFLAG_FLESH = 64;
float Q3SURFACEFLAG_NODRAW = 128;

float Q3SURFACEFLAG_METALSTEPS = 4096;
float Q3SURFACEFLAG_NOSTEPS = 8192;
float Q3SURFACEFLAG_NONSOLID = 16384;

.float viewzoom;

float(float number, float quantity) bitshift = #218;

float(string s) stof = #81;
float(string filename, float mode) fopen = #110;
void(float fhandle) fclose = #111;
string(float fhandle) fgets = #112;
void(float fhandle, string s, ...) fputs = #113;
float(string s) strlen = #114;
string(string s1, string s2, ...) strcat = #115;
string(string s, float start, float length) substring = #116;
vector(string s) stov = #117;
string(string s, ...) strzone = #118;
void(string s) strunzone = #119;

float FILE_READ = 0;
float FILE_APPEND = 1;
float FILE_WRITE = 2;

float(float modlindex) skel_create = #263;
float(float skel, entity ent, float modlindex, float retainfrac, float firstbone, float lastbone) skel_build = #264;
float(float skel) skel_get_numbones = #265;
string(float skel, float bonenum) skel_get_bonename = #266;
float(float skel, float bonenum) skel_get_boneparent = #267;
float(float skel, string tagname) skel_find_bone = #268;
vector(float skel, float bonenum) skel_get_bonerel = #269;
vector(float skel, float bonenum) skel_get_boneabs = #270;
void(float skel, float bonenum, vector org) skel_set_bone = #271;
void(float skel, float bonenum, vector org) skel_mul_bone = #272;
void(float skel, float startbone, float endbone, vector org) skel_mul_bones = #273;
void(float skeldst, float skelsrc, float startbone, float endbone) skel_copybones = #274;
void(float skel) skel_delete = #275;
float(float modlindex, string framename) frameforname = #276;
float(float modlindex, float framenum) frameduration = #277;

.float skeletonindex;
.float frame;
.float frame2;
.float frame3;
.float frame4;
.float lerpfrac;
.float lerpfrac3;
.float lerpfrac4;
.float frame1time;
.float frame2time;
.float frame3time;
.float frame4time;

float(float skel, float bonenum, string g1, string g2, string g3, string g4, string g5, string g6) example_skel_findbonegroup =
{
	local string bonename;
	while (bonenum >= 0)
	{
		bonename = skel_get_bonename(skel, bonenum);
		if (bonename == g1) return 1;
		if (bonename == g2) return 2;
		if (bonename == g3) return 3;
		if (bonename == g4) return 4;
		if (bonename == g5) return 5;
		if (bonename == g6) return 6;
		bonenum = skel_get_boneparent(skel, bonenum);
	}
	return 0;
};

void() example_skel_player_setup =
{
	self.skeletonindex = skel_create(self.modelindex);
};

void(float animmodelindex, float framegroup, float framegroupstarttime) example_skel_player_update_begin =
{

	self.frame = framegroup;
	self.frame2 = 0;
	self.frame3 = 0;
	self.frame4 = 0;
	self.frame1time = framegroupstarttime;
	self.frame2time = 0;
	self.frame3time = 0;
	self.frame4time = 0;
	self.lerpfrac = 0;
	self.lerpfrac3 = 0;
	self.lerpfrac4 = 0;
	skel_build(self.skeletonindex, self, animmodelindex, 0, 0, 100000);
};

void(float animmodelindex, float framegroup, float framegroupstarttime, float blendalpha, string groupbonename, string excludegroupname1, string excludegroupname2) example_skel_player_update_applyoverride =
{
	local float bonenum;
	local float numbones;
	self.frame = framegroup;
	self.frame2 = 0;
	self.frame3 = 0;
	self.frame4 = 0;
	self.frame1time = framegroupstarttime;
	self.frame2time = 0;
	self.frame3time = 0;
	self.frame4time = 0;
	self.lerpfrac = 0;
	self.lerpfrac3 = 0;
	self.lerpfrac4 = 0;
	bonenum = 0;
	numbones = skel_get_numbones(self.skeletonindex);
	while (bonenum < numbones)
	{
		if (example_skel_findbonegroup(self.skeletonindex, bonenum, groupbonename, excludegroupname1, excludegroupname2, "", "", "") == 1)
			skel_build(self.skeletonindex, self, animmodelindex, 1 - blendalpha, bonenum, bonenum + 1);
		bonenum = bonenum + 1;
	}
};

void(vector eyetarget, string bonename) example_skel_player_update_eyetarget =
{
	local float bonenum;
	local vector ang;
	local vector oldforward, oldright, oldup;
	local vector relforward, relright, relup, relorg;
	local vector boneforward, boneright, boneup, boneorg;
	local vector parentforward, parentright, parentup, parentorg;
	local vector u, v;
	local vector modeleyetarget;
	bonenum = skel_find_bone(self.skeletonindex, bonename) - 1;
	if (bonenum < 0)
		return;
	oldforward = v_forward;
	oldright = v_right;
	oldup = v_up;
	v = eyetarget - self.origin;
	modeleyetarget_x =   v * v_forward;
	modeleyetarget_y = 0-v * v_right;
	modeleyetarget_z =   v * v_up;

	relorg = skel_get_bonerel(self.skeletonindex, bonenum);
	relforward = v_forward;
	relright = v_right;
	relup = v_up;
	boneorg = skel_get_boneabs(self.skeletonindex, bonenum);
	boneforward = v_forward;
	boneright = v_right;
	boneup = v_up;
	parentorg = skel_get_boneabs(self.skeletonindex, skel_get_boneparent(self.skeletonindex, bonenum));
	parentforward = v_forward;
	parentright = v_right;
	parentup = v_up;

	u = modeleyetarget - boneorg;

	v_x = u * parentforward;
	v_y = u * parentright;
	v_z = u * parentup;
	ang = vectoangles2(v, relup);
	ang_x = 0 - ang_x;
	makevectors(ang);

	skel_set_bone(self.skeletonindex, bonenum, relorg);

	v_forward = oldforward;
	v_right = oldright;
	v_up = oldup;
};

void() example_skel_player_delete =
{
	skel_delete(self.skeletonindex);
	self.skeletonindex = 0;
};

void(entity e, string s) clientcommand = #440;
float(string s) tokenize = #441;
string(float n) argv = #442;

.string playermodel;
.string playerskin;

float EF_SELECTABLE = 16384;

.float cursor_active;
.vector cursor_screen;
.vector cursor_trace_start;
.vector cursor_trace_endpos;
.entity cursor_trace_ent;

.float light_lev;
.vector color;
.float style;
.float pflags;
.vector angles;
.float skin;

float PFLAGS_NOSHADOW = 1;
float PFLAGS_CORONA = 2;
float PFLAGS_FULLDYNAMIC = 128;

float checkpvs(vector viewpos, entity viewee) = #240;

float(string str, string sub, float startpos) strstrofs = #221;
float(string str, float ofs) str2chr = #222;
string(float c, ...) chr2str = #223;
string(float ccase, float calpha, float cnum, string s, ...) strconv = #224;
string(float chars, string s, ...) strpad = #225;
string(string info, string key, string value, ...) infoadd = #226;
string(string info, string key) infoget = #227;
float(string s1, string s2) strcmp = #228;
float(string s1, string s2, float len) strncmp = #228;
float(string s1, string s2) strcasecmp = #229;
float(string s1, string s2, float len) strncasecmp = #230;

float() buf_create = #460;
void(float bufhandle) buf_del = #461;
float(float bufhandle) buf_getsize = #462;
void(float bufhandle_from, float bufhandle_to) buf_copy = #463;
void(float bufhandle, float sortpower, float backward) buf_sort = #464;
string(float bufhandle, string glue) buf_implode = #465;
string(float bufhandle, float string_index) bufstr_get = #466;
void(float bufhandle, float string_index, string str) bufstr_set = #467;
float(float bufhandle, string str, float order) bufstr_add = #468;
void(float bufhandle, float string_index) bufstr_free = #469;

void(float bufhandle, string pattern, string antipattern) buf_cvarlist = #517;

const float MATCH_AUTO = 0;
const float MATCH_WHOLE = 1;
const float MATCH_LEFT = 2;
const float MATCH_RIGHT = 3;
const float MATCH_MIDDLE = 4;
const float MATCH_PATTERN = 5;

float(string filename, float bufhandle) buf_loadfile = #535;
float(float filehandle, float bufhandle, float startpos, float numstrings) buf_writefile = #536;
float(float bufhandle, string match, float matchrule, float startpos, float step) bufstr_find = #537;
float(string s, string pattern, float matchrule) matchpattern = #538;
float(string s, string pattern, float matchrule, float pos) matchpatternofs = #538;

string(string search, string replace, string subject) strreplace = #484;
string(string search, string replace, string subject) strireplace = #485;

void(float index, float type, ...) addstat = #232;

void(float pause) setpause = #531;

void coverage() = #642;

.string crypto_keyfp;
.string crypto_mykeyfp;
.string crypto_idfp;
.float crypto_idfp_signed;
.string crypto_encryptmethod;
.string crypto_signmethod;

float(string url, float id, string content_type, string delim, float buf, float keyid) crypto_uri_postbuf = #513;

float MOVETYPE_USER_FIRST = 128;
float MOVETYPE_USER_LAST = 191;

.float clipgroup;

float(string pattern, float caseinsensitive, float quiet, string packfile) search_packfile_begin = #444;

void(string cmdname) registercommand = #352;

entity(vector mins, vector maxs) findbox = #566;
entity(vector mins, vector maxs, .entity tofield) findbox_tofield = #566;
